admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 15001
static_resources:
  clusters:
  - name: provider
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: provider
        port_value: 20882


  listeners:
    name: listener_0
    metadata:
        filter_metadata:
            ## 表示从该listener_0 进入的流量请求,若没有带流量染色标记,默认会标为11111 标记
            config_downstream_color:
                value: "green"
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 20881
    filter_chains:
    - filters:
      - name: envoy.filters.network.dubbo_proxy
        config:
          stat_prefix: dubbo_proxy
          protocol_type: Dubbo
          serialization_type: Hessian2

      - name: envoy.tcp_proxy
        config:
          stat_prefix: ingress_tcp
          cluster: provider
          send_proxy_protocol: true
          access_log:
            - name: envoy.file_access_log
              config:
                path: "/var/log/envoy-access0.log"
