admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 25001
static_resources:
  clusters:
  - name: dubbo0|blue
    metadata:
      filter_metadata: 
         service_color: 
            value: "blue"

    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: localhost 
        port_value: 20880
  - name: dubbo0|green
    metadata:
      filter_metadata: 
         service_color: 
            value: "green"

    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: localhost 
        port_value: 21880



  listeners:
    name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 20882
    listener_filters:
    - name: envoy.listener.proxy_protocol
    filter_chains:
    - filters:
      - name: envoy.filters.network.dubbo_proxy
        config:
          stat_prefix: dubbo_proxy
          protocol_type: Dubbo
          serialization_type: Hessian2

      - name: envoy.tcp_proxy
        config:
          stat_prefix: ingress_tcp
          cluster: dubbo0
          send_proxy_protocol: true
          access_log:
            - name: envoy.file_access_log
              config:
                path: "/var/log/envoy-access2.log"
