FROM vifoggy/envoy:traffic-mark

RUN apt-get update && apt-get -q install -y python3 curl python3-pip libmysqlclient-dev
RUN pip3 install -q Flask==0.11.1 requests==2.18.4  mysqlclient
RUN apt-get update && apt-get upgrade -y && apt-get install -y iproute2 iptables
RUN apt-get install -y dnsutils
RUN apt-get install -y mysql-client
    
RUN mkdir /code
ADD ./service.py /code
ADD ./start_service_iptables.sh /usr/local/bin/start_service.sh
ADD ./istio-iptables.sh /usr/local/bin/istio-iptables.sh

RUN useradd demo_user
RUN chmod u+x /usr/local/bin/istio-iptables.sh


RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh
