version: '2'
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "7001"
      - "18001"
    ports:
      - "7001:7001"
      - "18001:18001"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service-iptables
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          -service1
    environment:
      - SERVICE_NAME=simple
    cap_add:
      - ALL
    expose:
      - "18080"
      - "28081"
    ports:
      - "18080:18080"
      - "28081:28081"

  service1-green:
    build:
      context: .
      dockerfile: Dockerfile-service-iptables
    volumes:
      - ./service-envoy-green.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service1-green
    environment:
      - SERVICE_NAME=green
    cap_add:
      - ALL
    expose:
      - "18081"
      - "28082"
    ports:
      - "18081:18080"
      - "28082:28081"

  service1-red:
    build:
      context: .
      dockerfile: Dockerfile-service-iptables
    volumes:
      - ./service-envoy-red.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service1-red
    environment:
      - SERVICE_NAME=red
    cap_add:
      - ALL
    expose:
      - "18082"
      - "28083"
    ports:
      - "18082:18080"
      - "28083:28081"

  mysql-envoy-proxy:
    build:
      context: .
      dockerfile: Dockerfile-mysql-proxy
    volumes:
      - ./mysql-envoy-proxy.yaml:/etc/mysql-envoy-proxy.yaml
    networks:
      envoymesh:
         aliases:
           - mysql-envoy-proxy
    expose:
      - "13306"
    ports:
      - "13306:13306"
  
  mysql:
   image: mysql:latest
   container_name: mysql-container
   expose:
     - 33306
   ports:
    - 33306:3306
   volumes:
    - ./person.sql:/docker-entrypoint-initdb.d/person.sql
   networks:
      envoymesh:
        aliases:
          - mysql
   environment:
    MYSQL_ROOT_PASSWORD: root123
    MYSQL_DATABASE: person
    MYSQL_USER: demo
    MYSQL_PASSWORD: demo123

  mysql-green:
   image: mysql:latest
   container_name: mysql-green-container
   expose:
     - 23306
   ports:
    - 23306:3306
   volumes:
    - ./person-green.sql:/docker-entrypoint-initdb.d/person-green.sql
   networks:
      envoymesh:
        aliases:
          - mysql-green
   environment:
    MYSQL_ROOT_PASSWORD: root123
    MYSQL_DATABASE: person
    MYSQL_USER: demo
    MYSQL_PASSWORD: demo123
        
networks:
  envoymesh: {}
