FROM vifoggy/envoy:traffic-mark

RUN apt-get update && apt-get -q install -y curl

COPY ./mysql-envoy-proxy.yaml /etc/mysql-envoy-proxy.yaml
CMD /usr/local/bin/envoy -c /etc/mysql-envoy-proxy.yaml --service-cluster msyql-envoy-proxy -l debug
