admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 15001
static_resources:
  clusters:
  - name: cluster_01
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: provider
        port_value: 20882

  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8550
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          url_transformer:
            - prefix: "/proxy"
            - prefix: /p 
            - prefix: /hash 
            - prefix: /chash 
            - prefix: /least  

          route_config:
            name: local_route
            virtual_hosts:
            - name: service_b
              domains: ["*"]
              routes:
              - match:
                  prefix: "/world"
                route:
                  cluster: cluster_01
                  timeout: "0.005s"
          http_filters:
          - name: envoy.router
